### ISSUE TITLE
Problema na execução

### ISSUE THREAD

**Issue by rafaelsilvestrini** [gstrtoint/playiptv#1]
Bom dia amigo, estou tentando dar o start e não funciona no node, não apresenta nenhum erro também... poderia me dar uma ajuda ?

estou com problemas em rodar video de url iptv em minhas aplicações, fica carregando e carregando, precisa de uma ajuda neste quesito, vê que utiliza algumas tecnologias e achei seu projeto poderia ajudar os meus....

atenciosamente

**Comment by gstrtoint** [comment]
Bom dia!

Posso tentar te ajudar! Você disse que está dando play e não roda. Chegou a
checar se a URL está funcionando? Utilize o VLC player pra testar a URL.
Qualquer coisa me chama no WhatsApp 31987176476

Abraço!

**Comment by gstrtoint** [comment]
É necessário a instalação da biblioteca ffmpeg no SO, e a mesma não estava instalada!
